# .github/workflows/deploy.yaml
name: deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Deploying to GitHub Pages...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: mlasalmo/mlasalmo.github.io
        DEPLOY_BRANCH: main
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Europe/Madrid
